### ISSUE TITLE
Fork to add copy/move files feature

### ISSUE THREAD

**Issue by forgondolin** [lusingander/stu#8]
Hey there, my bad if opening this issue is not the correct way of asking, but, can I fork your repo and try to add a copy/move (from a bucket to another) functionality? 

Thanks

**Comment by lusingander** [comment]
I thought that update features such as upload and copy were given low priority, because the program and UI become complicated. Also, as a practical matter, I think there are fewer cases where you would like to upload or copy using TUI compared to downloading.

However, I think it would be great if implemented well.

**Comment by lusingander** [comment]
As mentioned above, the update feature is a low priority and I have no plans to implement this, so I will close it for now.
If necessary, it would be good to reopen it and discuss the policy.
