### ISSUE TITLE
Example for config.toml with credentials

### ISSUE THREAD

**Issue by Nebucatnetzer** [lusingander/stu#9]
I'm struggling to provide a working config.toml or environment variables.
Should I be able to use the environment variables for AWS? Just like this `AWS_ENDPOINT_URL`?
For me this doesn't seem to be working.
Only when I provide the endpoint with `-e` I get a matching error message in the log file.

**Comment by lusingander** [comment]
At least for now, `config.toml` has nothing to do with connection information to AWS. The configurable items in `config.toml` are all described in [Config section of README](https://github.com/lusingander/stu?tab=readme-ov-file#config).

You should be able to connect to AWS the same way you would connect to the AWS CLI.
If you are unable to connect, please explain in more detail the environment variables and startup arguments you are specifying.

Also, `$STU_ROOT_DIR/error.log` may be useful if you encounter errors. However, since this file is intended to assist development, the necessary information may not be output in an easy-to-understand format.

**Comment by Nebucatnetzer** [comment]
Ah I misunderstood that then.
I will try to connect with the CLI first, see how that goes and report back.

**Comment by Nebucatnetzer** [comment]
Well it's a bit embarrassing but I've realised that the storage I'm trying to connect to only provides an Openstack Swift interface and no S3 interface.

BTW. would you mind if I package your application for NixOS?
I've basically already done it, I would just have to open a pull request at the Nixpkgs repository.

**Comment by lusingander** [comment]
> Well it's a bit embarrassing but I've realised that the storage I'm trying to connect to only provides an Openstack Swift interface and no S3 interface.

I see, no problem.

> BTW. would you mind if I package your application for NixOS?
> I've basically already done it, I would just have to open a pull request at the Nixpkgs repository.

I don't use Nix myself, but it sounds good.

**Comment by Nebucatnetzer** [comment]
https://github.com/NixOS/nixpkgs/pull/314539
